config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  
  get "tasks/:id", to: "tasks#show", as: :task

  get 'task/new', to: "tasks#new", as: :new_task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def edit
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
    <%= f.label :title%>
    <%= f.text_field :title%>
    <%= f.label :details %>
    <%= f.text_field :details%>
    <%= f.label :completed%>
    <%= f.number_field :completed%>
    <%= f.submit%>
<% end %>

app/views/tasks/index.html.erb
<!-- app/views/tasks/index.html.erb -->
<ul>
    <% @tasks.each do |task| %>
      <li><%= link_to task.title, task_path(task) %></li>
    <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
    <%= f.label :title%>
    <%= f.text_field :title%>
    <%= f.label :details %>
    <%= f.text_field :details%>
    <%= f.label :completed%>
    <%= f.number_field :completed%>
    <%= f.submit%>
<% end %>

app/views/tasks/show.html.erb
<li><%= @task.title %></li>
<li><%= @task.details %></li>
<li><%= @task.completed %></li>